### 일반 로그인
POST localhost:8080/login
Content-Type: application/json

{
  "id": "user1",
  "password": "hashedPassword123"
}

### 로그인 실패 요청
POST localhost:8080/login
Content-Type: application/json

{
  "id": "user1",
  "password": "hashedFail123"
}

### 로그아웃
GET localhost:8080/logout
Cookie: {redis session 쿠키 입력}

### 비회원 로그인
POST localhost:8080/login/non-member
Content-Type: application/json

{
  "name": "이승준",
  "password": "12345",
  "phone": "01012345678",
  "email": "lsj457@naver.com"
}