### 일반 로그인
POST localhost:8083/login
Content-Type: application/json

{
  "id": "user1",
  "password": "hashedPassword123"
}

### 관리자 로그인
POST localhost:8083/login
Content-Type: application/json

{
  "id": "admin",
  "password": "12345"
}

### 로그인 실패 요청
POST localhost:8080/login
Content-Type: application/json

{
  "id": "user1",
  "password": "hashedFail123"
}

### 로그아웃
GET localhost:8080/logout

### 토큰 재발급 요청
GET localhost:8083/auth/refreshToken
Cookie: refreshToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsInJvbGUiOiJST0xFX01FTUJFUiIsImlhdCI6MTczMDY5NDU3NCwiZXhwIjoxNzMxMjk5Mzc0LCJqdGkiOiJmNWYwY2E4MS0xZTVkLTQ3YWYtYWIwYS0zMGI4MGU3MjlkMzYifQ.pleShf57OU71_Ys9UGKZUl_OfqpJo88fqNL_ku1zoX4

### 프론트에서 로그인 완료시 다시 로그아웃후 로그인이 가능하도록 처리 해야함.

### 토큰에서 정보 가져오기
GET localhost:8083/auth/user-info
Cookie: accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsInJvbGUiOiJST0xFX01FTUJFUiIsImlhdCI6MTczMDY5NDU3NCwiZXhwIjoxNzMwNjk1NDc0LCJqdGkiOiIzOGQwNzJkMy1iZDU0LTRlODQtYjljMi01YWU3ZDY2ZjVmMzkifQ.rMvbriBtaXSshIZ2gZ37BDhscWmEKTS3pRHfq5adAzU